name: run build script

on: 
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Bash Script
        run: ./build.sh

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: caddy
          path: ./caddy


  release:
    runs-on: ubuntu-latest
    needs: [run-script]
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Create Tag
        run: |
          go_latest_version=$(curl -s https://go.dev/VERSION?m=text | head -n 1)
          caddy_latest_version=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r '.tag_name')

          tag_name="${go_latest_version}-caddy${caddy_latest_version}"

          git config --local user.email "taggerbot@empty.empty"
          git config --local user.name "taggerbot from github action"
          git tag $tag_name
          git push origin $tag_name

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            caddy
